apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-autz
  labels:
    app: ext-autz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-autz
  template:
    metadata:
      labels:
        app: ext-autz
      annotations:
        sidecar.istio.io/inject: "true"         
    spec:
      containers:
      - name: ext-autz
        image: nitinzzz/ext-autz-spring
        ports:
        - containerPort: 8080       
---        
apiVersion: v1
kind: Service
metadata:
  name: ext-authz-http
  labels:
    app: ext-autz
spec:
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080
    name: http
  selector:
    app: ext-autz