apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-configmaps
data:
   hostv1: istio-demo-v1-0
   hostv2: istio-demo-v1-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-demo-wrapper
  labels:
    app: istio-demo-wrapper
spec:
  selector:
    matchLabels:
      app: istio-demo-wrapper
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-demo-wrapper
    spec:   
      containers:
      - name: istio-demo-wrapper
        image: nitinzzz/istiodemowrapper:v1 
        env:
          - name: hostv1
            valueFrom:
             configMapKeyRef:
                name: spring-boot-configmaps
                key: hostv1   
          - name: hostv2
            valueFrom:
             configMapKeyRef:
                name: spring-boot-configmaps
                key: hostv2                         
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: istio-demo-wrapper
  labels:
    app: istio-demo-wrapper
spec:
  ports:
  - protocol: TCP 
    port: 8080
    name: http
  selector:
    app: istio-demo-wrapper
